import { jsPDF } from "jspdf";
import { PLACEHOLDER, type DraftDocument } from "./documentGen";

/**
 * Renders the same DraftDocument the preview and .txt use, so all three
 * formats come from one validated source. No LLM involved.
 *
 * Limitation: jsPDF's built-in fonts only cover Latin characters (WinAnsi);
 * production would embed a Unicode font (see README).
 */

const INK: [number, number, number] = [36, 0, 103];
const VIOLET: [number, number, number] = [79, 31, 191];
const LIME: [number, number, number] = [235, 255, 87];
const MUTED: [number, number, number] = [120, 110, 150];

const PAGE = { width: 210, height: 297, margin: 22 };
const CONTENT_WIDTH = PAGE.width - PAGE.margin * 2;
const BOTTOM = PAGE.height - 24;

export function documentToPdf(doc: DraftDocument): jsPDF {
  const pdf = new jsPDF({ unit: "mm", format: "a4", compress: false });
  pdf.setProperties({ title: doc.title, subject: doc.disclaimer, creator: "Document Intake Assistant" });
  let y = PAGE.margin;

  const ensureSpace = (needed: number) => {
    if (y + needed > BOTTOM) {
      pdf.addPage();
      y = PAGE.margin;
    }
  };

  // Disclaimer stamp
  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(9);
  const disclaimerLines = pdf.splitTextToSize(doc.disclaimer, CONTENT_WIDTH - 10) as string[];
  const boxHeight = disclaimerLines.length * 4.4 + 8;
  pdf.setFillColor(...LIME);
  pdf.setDrawColor(...INK);
  pdf.setLineWidth(0.6);
  pdf.rect(PAGE.margin, y, CONTENT_WIDTH, boxHeight, "FD");
  pdf.setTextColor(...INK);
  pdf.text(disclaimerLines, PAGE.margin + 5, y + 6.5);
  y += boxHeight + 14;

  // Title
  pdf.setFont("times", "bold");
  pdf.setFontSize(24);
  pdf.text(doc.title, PAGE.margin, y);
  y += 5;
  pdf.setLineWidth(0.8);
  pdf.line(PAGE.margin, y, PAGE.width - PAGE.margin, y);
  y += 12;

  // Sections
  for (const section of doc.sections) {
    ensureSpace(16);
    pdf.setFont("helvetica", "bold");
    pdf.setFontSize(9);
    pdf.setTextColor(...VIOLET);
    pdf.text(section.heading.toUpperCase(), PAGE.margin, y, { charSpace: 0.4 });
    y += 6.5;

    for (const line of section.body) {
      const missing = line.includes(PLACEHOLDER);
      pdf.setFont("times", missing ? "italic" : "normal");
      pdf.setFontSize(12);
      pdf.setTextColor(...(missing ? MUTED : INK));
      const wrapped = pdf.splitTextToSize(line, CONTENT_WIDTH) as string[];
      ensureSpace(wrapped.length * 5.6);
      pdf.text(wrapped, PAGE.margin, y);
      y += wrapped.length * 5.6 + 1.2;
    }
    y += 7;
  }

  // Footer on every page
  const pages = pdf.getNumberOfPages();
  for (let i = 1; i <= pages; i++) {
    pdf.setPage(i);
    pdf.setFont("helvetica", "normal");
    pdf.setFontSize(8);
    pdf.setTextColor(...MUTED);
    pdf.text("Fictional draft - not legal advice - generated by Document Intake Assistant", PAGE.margin, PAGE.height - 12);
    pdf.text(`Page ${i} of ${pages}`, PAGE.width - PAGE.margin, PAGE.height - 12, { align: "right" });
  }

  return pdf;
}
